server:
  port: 8080
  tomcat:
    max-http-form-post-size: 16777216


# db
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hasor
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # druid
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
      filter.stat.log-slow-sql: true
      filter.stat.slow-sql-millis: 1


# 是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY: true

# 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: true

# dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_API_URL: /api/

# dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/

# SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT: mysql